export interface TranscriptSegment {
  text: string;
  start: number;
  duration: number;
}

export interface TranscriptLanguage {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

interface CaptionTrack {
  baseUrl: string;
  languageCode?: string;
  kind?: string;
  name?: {
    simpleText?: string;
    runs?: Array<{ text: string }>;
  };
  vssId?: string;
}

interface TranscriptFetchAttempt {
  url: string;
  label: string;
}

export class YouTubeTranscriptAPI {
  private videoId: string;
  private playerResponse: any | null = null;
  private watchPageHtml: string | null = null;

  constructor(videoId: string) {
    this.videoId = videoId;
  }

  async getAvailableLanguages(): Promise<TranscriptLanguage[]> {
    const tracks = await this.getCaptionTracks();

    return tracks.map(track => ({
      languageCode: track.languageCode || '',
      name: this.getTrackName(track),
      isAutoGenerated: track.kind === 'asr' || track.vssId?.startsWith('a.') === true,
    }));
  }

  async fetchTranscript(languageCode?: string): Promise<TranscriptSegment[]> {
    const errors: string[] = [];

    try {
      const domSegments = await this.fetchTranscriptFromDomPanel();
      if (domSegments.length > 0) {
        return this.fillDurations(domSegments);
      }
      errors.push('YouTube transcript panel: empty parsed transcript');
    } catch (error) {
      errors.push(`YouTube transcript panel: ${this.getErrorMessage(error)}`);
    }

    try {
      const panelSegments = await this.fetchTranscriptFromPanelEndpoint();
      if (panelSegments.length > 0) {
        return this.fillDurations(panelSegments);
      }
      errors.push('transcript panel: empty parsed transcript');
    } catch (error) {
      errors.push(`transcript panel: ${this.getErrorMessage(error)}`);
    }

    try {
      const tracks = await this.getCaptionTracks();
      if (tracks.length === 0) {
        errors.push('caption tracks: none found');
      } else {
        const track = this.selectTrack(tracks, languageCode);
        const segments = await this.fetchTrackSegments(track);
        if (segments.length > 0) {
          return this.fillDurations(segments);
        }
        errors.push('caption tracks: empty parsed transcript');
      }
    } catch (error) {
      errors.push(`caption tracks: ${this.getErrorMessage(error)}`);
    }

    const fallbackTranscript = await this.fetchTranscriptThroughBackground();
    if (fallbackTranscript) {
      return [{ text: fallbackTranscript, start: 0, duration: 0 }];
    }

    throw new Error(`Could not extract readable transcript text. ${errors.join('; ')}`);
  }

  async getFormattedTranscript(languageCode?: string): Promise<string> {
    const segments = await this.fetchTranscript(languageCode);
    return segments
      .map(segment => segment.text)
      .join(' ')
      .replace(/\s+/g, ' ')
      .trim();
  }

  private async getCaptionTracks(): Promise<CaptionTrack[]> {
    const playerResponse = await this.getPlayerResponse();
    return playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];
  }

  private async getPlayerResponse(): Promise<any> {
    if (this.playerResponse) {
      return this.playerResponse;
    }

    this.playerResponse = this.extractPlayerResponse(document.documentElement.innerHTML);

    if (!this.playerResponse) {
      const response = await fetch(`https://www.youtube.com/watch?v=${encodeURIComponent(this.videoId)}&hl=en`, {
        credentials: 'include',
      });

      if (!response.ok) {
        throw new Error(`Could not load the YouTube watch page (${response.status}).`);
      }

      this.playerResponse = this.extractPlayerResponse(await response.text());
    }

    if (!this.playerResponse) {
      throw new Error('Could not find YouTube player data for this video.');
    }

    return this.playerResponse;
  }

  private async getWatchPageHtml(): Promise<string> {
    if (this.watchPageHtml) {
      return this.watchPageHtml;
    }

    const response = await fetch(`https://www.youtube.com/watch?v=${encodeURIComponent(this.videoId)}&hl=en`, {
      credentials: 'include',
    });

    if (!response.ok) {
      throw new Error(`Could not load the YouTube watch page (${response.status}).`);
    }

    this.watchPageHtml = await response.text();
    return this.watchPageHtml;
  }

  private async fetchTranscriptFromDomPanel(): Promise<TranscriptSegment[]> {
    let transcriptPanel = document.querySelector('ytd-transcript-renderer') as HTMLElement | null;

    if (!transcriptPanel) {
      await this.openTranscriptPanel();
      transcriptPanel = await this.waitForElement('ytd-transcript-renderer', 7000);
    }

    if (!transcriptPanel) {
      throw new Error('transcript panel did not open');
    }

    return await this.collectTranscriptSegmentsFromPanel(transcriptPanel);
  }

  private async openTranscriptPanel(): Promise<void> {
    const existingPanel = document.querySelector('ytd-transcript-renderer');
    if (existingPanel) {
      return;
    }

    await this.scrollToDescription();
    await this.expandDescriptionIfNeeded();

    const directButton = await this.waitForClickableByText(['show transcript'], 4000, this.getTranscriptSearchRoots());
    if (directButton) {
      directButton.click();
      return;
    }

    const fallbackDirectButton = await this.waitForClickableByText(['transcript'], 1500, this.getTranscriptSearchRoots());
    if (fallbackDirectButton) {
      fallbackDirectButton.click();
      return;
    }

    const moreActionsButton = this.findMoreActionsButton();
    if (moreActionsButton) {
      moreActionsButton.click();
      const menuItem = await this.waitForClickableByText(['show transcript', 'transcript'], 2500);
      if (menuItem) {
        menuItem.click();
        return;
      }
    }

    throw new Error('show transcript button was not found');
  }

  private async scrollToDescription(): Promise<void> {
    const description =
      (document.querySelector('ytd-watch-metadata #description') as HTMLElement | null) ||
      (document.querySelector('ytd-watch-metadata') as HTMLElement | null);

    if (description) {
      description.scrollIntoView({ block: 'center', behavior: 'auto' });
      await this.sleep(300);
    }
  }

  private async expandDescriptionIfNeeded(): Promise<void> {
    for (let index = 0; index < 3; index += 1) {
      const expandButton = this.findDescriptionExpandButton();
      if (!expandButton) {
        return;
      }

      expandButton.click();
      await this.sleep(700);
    }
  }

  private findDescriptionExpandButton(): HTMLElement | null {
    const roots = this.getTranscriptSearchRoots();
    const explicitSelectors = [
      '#description #expand',
      'ytd-watch-metadata #expand',
      'ytd-text-inline-expander #expand',
      'tp-yt-paper-button#expand',
      'button[aria-label*="more" i]',
    ];

    for (const root of roots) {
      for (const selector of explicitSelectors) {
        const elements = Array.from(root.querySelectorAll(selector)) as HTMLElement[];
        const button = elements.find(element => this.isVisible(element));
        if (button) {
          return button;
        }
      }
    }

    return this.findClickableByText(['...more', 'show more'], roots);
  }

  private getTranscriptSearchRoots(): ParentNode[] {
    const selectors = [
      'ytd-watch-metadata',
      '#description',
      'ytd-expandable-video-description-body-renderer',
      'ytd-structured-description-content-renderer',
    ];
    const roots: ParentNode[] = [];

    for (const selector of selectors) {
      const element = document.querySelector(selector);
      if (element) {
        roots.push(element);
      }
    }

    roots.push(document);
    return roots;
  }

  private findMoreActionsButton(): HTMLElement | null {
    const selectors = [
      'button[aria-label*="More actions" i]',
      'button[aria-label*="More" i]',
      'ytd-menu-renderer button',
      '#top-level-buttons-computed button',
    ];

    for (const selector of selectors) {
      const elements = Array.from(document.querySelectorAll(selector)) as HTMLElement[];
      const button = elements.find(element => this.isVisible(element));
      if (button) {
        return button;
      }
    }

    return null;
  }

  private async waitForElement(selector: string, timeoutMs: number): Promise<HTMLElement | null> {
    const startedAt = Date.now();

    while (Date.now() - startedAt < timeoutMs) {
      const element = document.querySelector(selector) as HTMLElement | null;
      if (element) {
        return element;
      }

      await this.sleep(150);
    }

    return null;
  }

  private async waitForClickableByText(
    labels: string[],
    timeoutMs: number,
    roots: ParentNode[] = [document]
  ): Promise<HTMLElement | null> {
    const startedAt = Date.now();

    while (Date.now() - startedAt < timeoutMs) {
      const element = this.findClickableByText(labels, roots);
      if (element) {
        return element;
      }

      await this.sleep(150);
    }

    return null;
  }

  private findClickableByText(labels: string[], roots: ParentNode[] = [document]): HTMLElement | null {
    const normalizedLabels = labels.map(label => this.normalizeText(label));
    const selectors = [
      'button',
      'tp-yt-paper-button',
      'yt-button-shape button',
      'ytd-button-renderer button',
      'ytd-menu-service-item-renderer',
      'yt-formatted-string',
      '[role="button"]',
    ];

    for (const root of roots) {
      for (const selector of selectors) {
        const elements = Array.from(root.querySelectorAll(selector)) as HTMLElement[];

        for (const element of elements) {
          if (!this.isVisible(element)) {
            continue;
          }

          const text = this.normalizeText(`${element.textContent || ''} ${element.getAttribute('aria-label') || ''}`);
          if (normalizedLabels.some(label => text.includes(label))) {
            const clickable = element.closest('button, tp-yt-paper-button, ytd-menu-service-item-renderer, [role="button"]') as HTMLElement | null;
            return clickable || element;
          }
        }
      }
    }

    return null;
  }

  private async collectTranscriptSegmentsFromPanel(panel: HTMLElement): Promise<TranscriptSegment[]> {
    const seen = new Set<string>();
    const segments: TranscriptSegment[] = [];
    const scrollContainer =
      (panel.querySelector('#segments-container') as HTMLElement | null) ||
      (panel.querySelector('ytd-transcript-segment-list-renderer') as HTMLElement | null) ||
      panel;

    for (let index = 0; index < 25; index += 1) {
      this.parseDomTranscriptSegments(panel, seen, segments);

      const previousScrollTop = scrollContainer.scrollTop;
      scrollContainer.scrollTop += Math.max(scrollContainer.clientHeight, 500);
      await this.sleep(180);

      if (scrollContainer.scrollTop === previousScrollTop) {
        break;
      }
    }

    this.parseDomTranscriptSegments(panel, seen, segments);
    return segments.sort((a, b) => a.start - b.start);
  }

  private parseDomTranscriptSegments(panel: HTMLElement, seen: Set<string>, segments: TranscriptSegment[]): void {
    const nodes = Array.from(
      panel.querySelectorAll('ytd-transcript-segment-renderer, yt-formatted-string.segment-text')
    ) as HTMLElement[];

    for (const node of nodes) {
      const container = (node.closest('ytd-transcript-segment-renderer') as HTMLElement | null) || node;
      const timeText =
        container.querySelector('.segment-timestamp')?.textContent?.trim() ||
        container.querySelector('[class*="timestamp"]')?.textContent?.trim() ||
        '';
      const text =
        container.querySelector('.segment-text')?.textContent?.trim() ||
        container.textContent?.replace(timeText, '').replace(/\s+/g, ' ').trim() ||
        '';

      if (!text) {
        continue;
      }

      const key = `${timeText}|${text}`;
      if (seen.has(key)) {
        continue;
      }

      seen.add(key);
      segments.push({
        text,
        start: this.parseTimestamp(timeText),
        duration: 0,
      });
    }
  }

  private parseTimestamp(value: string): number {
    if (!value) {
      return 0;
    }

    const parts = value
      .split(':')
      .map(part => Number(part.trim()))
      .filter(part => Number.isFinite(part));

    if (parts.length === 3) {
      return parts[0] * 3600 + parts[1] * 60 + parts[2];
    }

    if (parts.length === 2) {
      return parts[0] * 60 + parts[1];
    }

    return parts[0] || 0;
  }

  private extractPlayerResponse(source: string): any | null {
    const marker = 'ytInitialPlayerResponse';
    let searchFrom = 0;

    while (searchFrom < source.length) {
      const markerIndex = source.indexOf(marker, searchFrom);
      if (markerIndex === -1) {
        return null;
      }

      const objectStart = source.indexOf('{', markerIndex + marker.length);
      if (objectStart === -1) {
        return null;
      }

      const objectText = this.extractBalancedJsonObject(source, objectStart);
      if (!objectText) {
        searchFrom = markerIndex + marker.length;
        continue;
      }

      try {
        return JSON.parse(objectText);
      } catch (error) {
        searchFrom = objectStart + 1;
      }
    }

    return null;
  }

  private async fetchTranscriptFromPanelEndpoint(): Promise<TranscriptSegment[]> {
    const sources = [document.documentElement.innerHTML];
    const errors: string[] = [];

    try {
      sources.push(await this.getWatchPageHtml());
    } catch (error) {
      errors.push(`watch page fetch: ${this.getErrorMessage(error)}`);
    }

    for (const source of sources) {
      try {
        const initialData = this.extractJsonByMarker(source, 'ytInitialData');
        if (!initialData) {
          errors.push('ytInitialData not found');
          continue;
        }

        const endpoint = this.findTranscriptEndpoint(initialData);
        if (!endpoint?.params) {
          errors.push('getTranscriptEndpoint params not found');
          continue;
        }

        const config = this.extractYouTubeConfig(source);
        if (!config.apiKey) {
          errors.push('InnerTube API key not found');
          continue;
        }

        const response = await fetch(
          `https://www.youtube.com/youtubei/v1/get_transcript?key=${encodeURIComponent(config.apiKey)}&prettyPrint=false`,
          {
            method: 'POST',
            credentials: 'include',
            headers: {
              'Content-Type': 'application/json',
              'X-YouTube-Client-Name': String(config.clientNameHeader || '1'),
              'X-YouTube-Client-Version': config.clientVersion,
            },
            body: JSON.stringify({
              context: config.context,
              params: endpoint.params,
            }),
          }
        );

        if (!response.ok) {
          errors.push(`get_transcript HTTP ${response.status}`);
          continue;
        }

        const data = await response.json();
        const segments = this.parseTranscriptPanelResponse(data);

        if (segments.length > 0) {
          return segments;
        }

        errors.push('get_transcript response had no transcript segments');
      } catch (error) {
        errors.push(this.getErrorMessage(error));
      }
    }

    throw new Error(errors.join('; '));
  }

  private extractJsonByMarker(source: string, marker: string): any | null {
    let searchFrom = 0;

    while (searchFrom < source.length) {
      const markerIndex = source.indexOf(marker, searchFrom);
      if (markerIndex === -1) {
        return null;
      }

      const objectStart = source.indexOf('{', markerIndex + marker.length);
      if (objectStart === -1) {
        return null;
      }

      const objectText = this.extractBalancedJsonObject(source, objectStart);
      if (!objectText) {
        searchFrom = markerIndex + marker.length;
        continue;
      }

      try {
        return JSON.parse(objectText);
      } catch (error) {
        searchFrom = objectStart + 1;
      }
    }

    return null;
  }

  private findTranscriptEndpoint(data: any): any | null {
    if (!data || typeof data !== 'object') {
      return null;
    }

    if (data.getTranscriptEndpoint?.params) {
      return data.getTranscriptEndpoint;
    }

    if (Array.isArray(data)) {
      for (const item of data) {
        const found = this.findTranscriptEndpoint(item);
        if (found) {
          return found;
        }
      }
      return null;
    }

    for (const value of Object.values(data)) {
      const found = this.findTranscriptEndpoint(value);
      if (found) {
        return found;
      }
    }

    return null;
  }

  private extractYouTubeConfig(source: string): {
    apiKey: string;
    clientVersion: string;
    clientNameHeader: string;
    context: any;
  } {
    const ytcfg = this.extractYtcfg(source);
    const apiKey = ytcfg?.INNERTUBE_API_KEY || this.extractStringValue(source, 'INNERTUBE_API_KEY') || '';
    const clientVersion =
      ytcfg?.INNERTUBE_CLIENT_VERSION ||
      this.extractStringValue(source, 'INNERTUBE_CLIENT_VERSION') ||
      '2.20250101.00.00';
    const clientName = ytcfg?.INNERTUBE_CLIENT_NAME || 'WEB';
    const clientNameHeader = String(ytcfg?.INNERTUBE_CONTEXT_CLIENT_NAME || 1);
    const context =
      ytcfg?.INNERTUBE_CONTEXT ||
      {
        client: {
          clientName,
          clientVersion,
          hl: 'en',
          gl: 'US',
        },
      };

    return {
      apiKey,
      clientVersion,
      clientNameHeader,
      context,
    };
  }

  private extractYtcfg(source: string): any | null {
    let searchFrom = 0;
    const marker = 'ytcfg.set';
    const mergedConfig: any = {};
    let foundConfig = false;

    while (searchFrom < source.length) {
      const markerIndex = source.indexOf(marker, searchFrom);
      if (markerIndex === -1) {
        return foundConfig ? mergedConfig : null;
      }

      const objectStart = source.indexOf('{', markerIndex + marker.length);
      if (objectStart === -1) {
        return foundConfig ? mergedConfig : null;
      }

      const objectText = this.extractBalancedJsonObject(source, objectStart);
      if (!objectText) {
        searchFrom = markerIndex + marker.length;
        continue;
      }

      try {
        Object.assign(mergedConfig, JSON.parse(objectText));
        foundConfig = true;
        searchFrom = objectStart + objectText.length;
      } catch (error) {
        searchFrom = objectStart + 1;
      }
    }

    return foundConfig ? mergedConfig : null;
  }

  private extractStringValue(source: string, key: string): string | null {
    const escapedKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const match = source.match(new RegExp(`"${escapedKey}"\\s*:\\s*"([^"]+)"`));
    return match?.[1] || null;
  }

  private parseTranscriptPanelResponse(data: any): TranscriptSegment[] {
    return this.findTranscriptSegmentRenderers(data)
      .map(renderer => {
        const start = Number(renderer.startMs || 0) / 1000;
        const end = Number(renderer.endMs || 0) / 1000;

        return {
          text: this.extractRunsText(renderer.snippet || renderer),
          start,
          duration: end > start ? end - start : 0,
        };
      })
      .filter(segment => segment.text.length > 0);
  }

  private findTranscriptSegmentRenderers(data: any): any[] {
    if (!data || typeof data !== 'object') {
      return [];
    }

    if (data.transcriptSegmentRenderer) {
      return [data.transcriptSegmentRenderer];
    }

    const renderers: any[] = [];
    const values = Array.isArray(data) ? data : Object.values(data);

    for (const value of values) {
      renderers.push(...this.findTranscriptSegmentRenderers(value));
    }

    return renderers;
  }

  private extractRunsText(data: any): string {
    if (!data || typeof data !== 'object') {
      return '';
    }

    if (typeof data.simpleText === 'string') {
      return data.simpleText.replace(/\s+/g, ' ').trim();
    }

    if (Array.isArray(data.runs)) {
      return data.runs
        .map((run: any) => run?.text || '')
        .join('')
        .replace(/\s+/g, ' ')
        .trim();
    }

    return '';
  }

  private extractBalancedJsonObject(source: string, start: number): string | null {
    let depth = 0;
    let inString = false;
    let escaped = false;

    for (let index = start; index < source.length; index += 1) {
      const char = source[index];

      if (inString) {
        if (escaped) {
          escaped = false;
        } else if (char === '\\') {
          escaped = true;
        } else if (char === '"') {
          inString = false;
        }
        continue;
      }

      if (char === '"') {
        inString = true;
      } else if (char === '{') {
        depth += 1;
      } else if (char === '}') {
        depth -= 1;
        if (depth === 0) {
          return source.slice(start, index + 1);
        }
      }
    }

    return null;
  }

  private selectTrack(tracks: CaptionTrack[], languageCode?: string): CaptionTrack {
    if (languageCode) {
      const selectedTrack = tracks.find(track => track.languageCode === languageCode);
      if (selectedTrack) {
        return selectedTrack;
      }
    }

    return (
      tracks.find(track => track.languageCode === 'en' && track.kind !== 'asr') ||
      tracks.find(track => track.languageCode === 'en') ||
      tracks.find(track => track.languageCode?.startsWith('en')) ||
      tracks[0]
    );
  }

  private async fetchTrackSegments(track: CaptionTrack): Promise<TranscriptSegment[]> {
    if (!track.baseUrl) {
      throw new Error('The selected caption track does not include a transcript URL.');
    }

    const attempts = this.createCaptionFetchAttempts(track.baseUrl);
    const errors: string[] = [];

    for (const attempt of attempts) {
      try {
        const response = await fetch(attempt.url, { credentials: 'include' });

        if (!response.ok) {
          errors.push(`${attempt.label}: HTTP ${response.status}`);
          continue;
        }

        const responseText = await response.text();
        const segments = this.parseTranscriptResponse(responseText);

        if (segments.length > 0) {
          return segments;
        }

        errors.push(`${attempt.label}: empty parsed transcript`);
      } catch (error) {
        errors.push(`${attempt.label}: ${this.getErrorMessage(error)}`);
      }
    }

    const fallbackTranscript = await this.fetchTranscriptThroughBackground();
    if (fallbackTranscript) {
      return [{ text: fallbackTranscript, start: 0, duration: 0 }];
    }

    throw new Error(`Could not parse readable transcript text. Tried ${errors.join('; ')}`);
  }

  private createCaptionFetchAttempts(baseUrl: string): TranscriptFetchAttempt[] {
    const formats = ['json3', 'srv3', 'srv1', 'ttml', 'vtt'];
    const attempts: TranscriptFetchAttempt[] = [];
    const seen = new Set<string>();

    for (const format of formats) {
      const url = new URL(baseUrl);
      url.searchParams.set('fmt', format);
      this.addFetchAttempt(attempts, seen, url.toString(), format);
    }

    this.addFetchAttempt(attempts, seen, baseUrl, 'original');

    return attempts;
  }

  private addFetchAttempt(
    attempts: TranscriptFetchAttempt[],
    seen: Set<string>,
    url: string,
    label: string
  ): void {
    if (seen.has(url)) {
      return;
    }

    seen.add(url);
    attempts.push({ url, label });
  }

  private parseTranscriptResponse(responseText: string): TranscriptSegment[] {
    const trimmed = responseText.trim();

    if (!trimmed) {
      return [];
    }

    if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
      try {
        const jsonSegments = this.parseJsonTranscript(JSON.parse(trimmed));
        if (jsonSegments.length > 0) {
          return jsonSegments;
        }
      } catch (error) {
        // Fall through to XML/VTT parsing. Some caption endpoints mislabel content.
      }
    }

    if (trimmed.startsWith('WEBVTT')) {
      return this.parseVttTranscript(trimmed);
    }

    return this.parseXmlTranscript(trimmed);
  }

  private async fetchTranscriptThroughBackground(): Promise<string | null> {
    try {
      const response = await chrome.runtime.sendMessage({
        action: 'FETCH_TRANSCRIPT_BACKGROUND',
        payload: { videoId: this.videoId },
      });

      if (response?.success && typeof response.transcript === 'string') {
        const transcript = response.transcript.replace(/\s+/g, ' ').trim();
        return transcript || null;
      }

      return null;
    } catch (error) {
      return null;
    }
  }

  private parseJsonTranscript(data: any): TranscriptSegment[] {
    const events = Array.isArray(data?.events) ? data.events : this.findArrayByKey(data, 'events');

    return events
      .map((event: any) => {
        const text = this.extractJsonEventText(event);

        return {
          text,
          start: Number(event.tStartMs || 0) / 1000,
          duration: Number(event.dDurationMs || 0) / 1000,
        };
      })
      .filter((segment: TranscriptSegment) => segment.text.length > 0);
  }

  private extractJsonEventText(event: any): string {
    if (Array.isArray(event?.segs)) {
      const text = event.segs
        .map((segment: any) => segment?.utf8 || segment?.text || '')
        .join('');

      if (text.trim()) {
        return text.replace(/\s+/g, ' ').trim();
      }
    }

    if (typeof event?.utf8 === 'string') {
      return event.utf8.replace(/\s+/g, ' ').trim();
    }

    if (typeof event?.text === 'string') {
      return event.text.replace(/\s+/g, ' ').trim();
    }

    if (typeof event?.simpleText === 'string') {
      return event.simpleText.replace(/\s+/g, ' ').trim();
    }

    if (Array.isArray(event?.runs)) {
      return event.runs
        .map((run: any) => run?.text || '')
        .join('')
        .replace(/\s+/g, ' ')
        .trim();
    }

    return '';
  }

  private findArrayByKey(data: any, key: string): any[] {
    if (!data || typeof data !== 'object') {
      return [];
    }

    if (Array.isArray(data?.[key])) {
      return data[key];
    }

    for (const value of Object.values(data)) {
      if (!value || typeof value !== 'object') {
        continue;
      }

      const found = this.findArrayByKey(value, key);
      if (found.length > 0) {
        return found;
      }
    }

    return [];
  }

  private parseXmlTranscript(xml: string): TranscriptSegment[] {
    const document = new DOMParser().parseFromString(xml, 'text/xml');
    const parseError = document.querySelector('parsererror');
    if (parseError) {
      return [];
    }

    const textNodes = Array.from(document.querySelectorAll('text'));

    if (textNodes.length > 0) {
      return textNodes
        .map(node => ({
          text: (node.textContent || '').replace(/\s+/g, ' ').trim(),
          start: this.readTimestamp(node, 'start', 't'),
          duration: this.readDuration(node, 'dur', 'd'),
        }))
        .filter(segment => segment.text.length > 0);
    }

    const phraseNodes = Array.from(document.querySelectorAll('p, s'));
    return phraseNodes
      .map(node => ({
        text: (node.textContent || '').replace(/\s+/g, ' ').trim(),
        start: this.readTimestamp(node, 'start', 't'),
        duration: this.readDuration(node, 'dur', 'd'),
      }))
      .filter(segment => segment.text.length > 0);
  }

  private parseVttTranscript(vtt: string): TranscriptSegment[] {
    const segments: TranscriptSegment[] = [];
    const blocks = vtt.replace(/\r/g, '').split(/\n{2,}/);

    for (const block of blocks) {
      const lines = block
        .split('\n')
        .map(line => line.trim())
        .filter(Boolean);

      const timingIndex = lines.findIndex(line => line.includes('-->'));
      if (timingIndex === -1) {
        continue;
      }

      const [startText, endText] = lines[timingIndex].split('-->').map(part => part.trim().split(/\s+/)[0]);
      const text = lines
        .slice(timingIndex + 1)
        .join(' ')
        .replace(/<[^>]+>/g, '')
        .replace(/\s+/g, ' ')
        .trim();

      if (!text) {
        continue;
      }

      const start = this.parseVttTime(startText);
      const end = this.parseVttTime(endText);

      segments.push({
        text,
        start,
        duration: Math.max(end - start, 0),
      });
    }

    return segments;
  }

  private parseVttTime(value: string): number {
    const parts = value.split(':').map(part => Number(part.replace(',', '.')));

    if (parts.length === 3) {
      return parts[0] * 3600 + parts[1] * 60 + parts[2];
    }

    if (parts.length === 2) {
      return parts[0] * 60 + parts[1];
    }

    return Number(value) || 0;
  }

  private readTimestamp(node: Element, secondsAttr: string, millisecondsAttr: string): number {
    const secondsValue = node.getAttribute(secondsAttr);
    if (secondsValue !== null) {
      return Number(secondsValue) || 0;
    }

    const millisecondsValue = node.getAttribute(millisecondsAttr);
    return millisecondsValue !== null ? (Number(millisecondsValue) || 0) / 1000 : 0;
  }

  private readDuration(node: Element, secondsAttr: string, millisecondsAttr: string): number {
    const secondsValue = node.getAttribute(secondsAttr);
    if (secondsValue !== null) {
      return Number(secondsValue) || 0;
    }

    const millisecondsValue = node.getAttribute(millisecondsAttr);
    return millisecondsValue !== null ? (Number(millisecondsValue) || 0) / 1000 : 0;
  }

  private fillDurations(segments: TranscriptSegment[]): TranscriptSegment[] {
    return segments.map((segment, index) => {
      if (segment.duration > 0) {
        return segment;
      }

      const nextSegment = segments[index + 1];
      return {
        ...segment,
        duration: nextSegment ? Math.max(nextSegment.start - segment.start, 1) : 5,
      };
    });
  }

  private getTrackName(track: CaptionTrack): string {
    return track.name?.simpleText || track.name?.runs?.map(run => run.text).join('') || track.languageCode || 'Transcript';
  }

  private normalizeText(value: string): string {
    return value.replace(/\s+/g, ' ').trim().toLowerCase();
  }

  private isVisible(element: HTMLElement): boolean {
    const rect = element.getBoundingClientRect();
    const style = window.getComputedStyle(element);
    return rect.width > 0 && rect.height > 0 && style.visibility !== 'hidden' && style.display !== 'none';
  }

  private sleep(ms: number): Promise<void> {
    return new Promise(resolve => window.setTimeout(resolve, ms));
  }

  private getErrorMessage(error: unknown): string {
    return error instanceof Error ? error.message : String(error);
  }
}
